### ISSUE TITLE
cake-contrib user on NuGet

### ISSUE THREAD

**Issue by gep13** [ecampidoglio/Cake.Curl#1]
@ecampidoglio what are your thoughts on doing this?

This was discussed here:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

https://www.nuget.org/profiles/cake-contrib

Would you be interested in doing this for Cake.Curl? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by ecampidoglio** [comment]
@gep13 While I understand the premise of this initiative—and I _do_ agree that it brings value to the community—I'd like to wait before moving Cake.Curl to the [cake-contrib](https://github.com/cake-contrib) org just yet.

**Comment by gep13** [comment]
@ecampidoglio yip, no issues there. The main thing that we are looking for here is adding the additional owner to the nuget package. Moving to the cake-contrib organisation is definitely not a requirement.

**Comment by ecampidoglio** [comment]
Done.

https://twitter.com/ecampidoglio/status/841577677215657984
