### ISSUE TITLE
Add support for retry options

### ISSUE THREAD

**Issue by ecampidoglio** [ecampidoglio/Cake.Curl#12]
Curl has built-in functionality to automatically *retry* a failed request. This behavior is controlled primarily with three options:

- [`--retry <num>`](https://curl.haxx.se/docs/manpage.html#--retry) the number of time curl should retry the request before giving up
- [`--retry-delay <seconds>` ](https://curl.haxx.se/docs/manpage.html#--retry-delay)the amount of time to wait between retries
- [`--retry-max-time <seconds>`](https://curl.haxx.se/docs/manpage.html#--retry-max-time) the maximum amount of time to wait before retries

By default, curl will increment the delay between attempts by *doubling* the last waiting time, starting from 1 second until it reaches the value specified in `--retry-max-time` or 10 minutes. Although this behavior should cover most scenarios, it's possible to override it by setting a fixed delay right from the start with the `--retry-delay` option

It would be nice if Cake.Curl exposed these options through the `CurlSettings` class.

**Comment by deqenq** [comment]
Can I take care of this issue? I also suggest to support option `--retry-connrefused` which was added in Curl version 7.52.0.

**Comment by ecampidoglio** [comment]
@deqenq Sure! I think it's a good idea to include [`--retry-connrefused`](https://curl.haxx.se/docs/manpage.html#--retry-connrefused), but I would rather treat [`--max-time`](https://curl.haxx.se/docs/manpage.html#-m) and [`--connect-timeout`](https://curl.haxx.se/docs/manpage.html#--connect-timeout) as a separate feature. Even though they do affect the retry mechanism, these options have a larger scope.

**Comment by deqenq** [comment]
@ecampidoglio PR sent. Added configuration options:
- [--retry](https://curl.haxx.se/docs/manpage.html#--retry)
- [--retry-delay](https://curl.haxx.se/docs/manpage.html#--retry-delay)
- [--retry-max-time](https://curl.haxx.se/docs/manpage.html#--retry-max-time)
- [--retry-connrefused](https://curl.haxx.se/docs/manpage.html#--retry-connrefused) 

Later I will add these two options in separate PR:
- [--max-time](https://curl.haxx.se/docs/manpage.html#-m)
- [--connect-timeout](https://curl.haxx.se/docs/manpage.html#--connect-timeout)

**Comment by ecampidoglio** [comment]
@deqenq Merged in 1bb6a24. Thank you for your contribution! 🎉
