### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [ecampidoglio/Cake.Curl#2]
This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#152

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by gep13** [comment]
@ecampidoglio **NOTE** I would actually hold off on doing this suggestion, if you agree with it.

We are almost at the shipping point with a new version of the website, so the files that will need changed are not as shown in the above PR, but they will be similar.

You could be our guinea for creating a PR to the new site 😄

**Comment by ecampidoglio** [comment]
@gep13 Sounds good to me 👍

**Comment by gep13** [comment]
@ecampidoglio perfect.  We have just merged the new website into develop branch.  So you should be in a position to submit a PR to this folder:

https://github.com/cake-build/website/tree/develop/addins

Idea would be to create a new file for your Addin.  Let me know if you have any questions.

**Comment by ecampidoglio** [comment]
@gep13 Sure. One question: are there any predefined/preferred categories for the add-ins?

**Comment by gep13** [comment]
@ecampidoglio no, nothing defined. Have a look at what is already there, and if there is one that makes sense, slot it in there, or create a new one.

**Comment by ecampidoglio** [comment]
@gep I just submitted cake-build/website#254 but the build is failing because Cake.Curl is still in prerelease on NuGet. I'll release it as stable later today.

**Comment by gep** [comment]
@ecampidoglio you ment @gep13

**Comment by ecampidoglio** [comment]
@gep Corrected. Sorry about that.

**Comment by ecampidoglio** [comment]
Closed by cake-build/website#254.
