### ISSUE TITLE
Test class should use its corresponding fixture class

### ISSUE THREAD

**Issue by deqenq** [ecampidoglio/Cake.Curl#20]
@ecampidoglio  I noticed that test <code>Should_Not_Set_The_Location_Option_As_Argument</code> in file CurlDownloadMultipleFilesTests.cs uses <code>CurlDownloadFileFixture</code> instead of <code>CurlDownloadMultipleFilesFixture</code>. The same mistake is in test <code>Should_Not_Set_The_Fail_Option_As_Argument</code>.

The same mistake is in CurlUploadFileTests.cs (here should be used <code>CurlUploadFileFixture</code>).

If this is bug, I will fix it.

**Comment by ecampidoglio** [comment]
@deqenq Good catch! It totally slipped through. You’re very welcome to fix it, if you’re so inclined. 👍

**Comment by ecampidoglio** [comment]
@deqenq Merged in e91add9. Thank you for your contribution! 🎉
