### ISSUE TITLE
Inconsistent cake version

### ISSUE THREAD

**Issue by deqenq** [ecampidoglio/Cake.Curl#23]
In file `build.ps1` there is defined older version of cake `$CAKE_VERSION = "0.23.0"` while in proj files and `build.sh` there is version 0.30.0. It would be nice to align these versions.
As of today the latest [Cake](https://www.nuget.org/packages/Cake/) version is 0.32.1, so maybe it could be the opportunity to update and align all to the latest version?

**Comment by ecampidoglio** [comment]
I generally prefer to compile against the _lowest_ possible version of Cake that's still compatible with the lastest one (i.e. running the script doesn't generate a warning). Right now, that's still version [0.30.0](https://github.com/cake-build/cake/releases/tag/v0.30.0) if I'm not mistaken.

I agree that we should build the addin using the same version of Cake as the one we link against. That means both bootstrappers should use version `0.30.0`.

**Comment by ecampidoglio** [comment]
Merged in 573dd37. Thank you for your contribution! 🎉
