### ISSUE TITLE
Add support for additional retry options

### ISSUE THREAD

**Issue by deqenq** [ecampidoglio/Cake.Curl#26]
Add additional retry options to `CurlSettings` class [--max-time](https://curl.haxx.se/docs/manpage.html#-m) and [--connect-timeout](https://curl.haxx.se/docs/manpage.html#--connect-timeout) as mentioned in this [issue comment](https://github.com/ecampidoglio/Cake.Curl/issues/12#issuecomment-468926624).
These options support decimal value since curl version 7.32.0. Accepted decimal separator is set by locale settings - see  [documentation](https://ec.haxx.se/usingcurl-timeouts.html).

**Comment by ecampidoglio** [comment]
@deqenq Merged in 65c6f6e. Thank you for your contribution! 🎉
