### ISSUE TITLE
Curl executable

### ISSUE THREAD

**Issue by matkoch** [ecampidoglio/Cake.Curl#3]
I guess there is no way around of installing curl to `path` ?

**Comment by ecampidoglio** [comment]
You can also specify the path to the _curl_ executable using the [`ToolSettings.ToolPath`](http://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/F6956DA8) property:

```csharp
Task("Download")
    .Does(() =>
{
    CurlDownloadFile(
        new Uri("http://host/file.txt"),
        new CurlDownloadSettings
        {
            ToolPath = "/path/to/curl"
        });
});
```

**Comment by gep13** [comment]
@matkoch assuming that you are on a Windows Machine, you could use chocolatey to fetch and install curl, which is a simple `choco install curl`, which puts the curl.exe on your path.  

If you wanted to go one step further, you could use the [ChocolateyInstall](http://cakebuild.net/api/Cake.Common.Tools.Chocolatey/ChocolateyAliases/B1E32DCB) alias to install curl as part of your build process.  

And if you wanted to go one step even further, you could try out my new Module (which hasn't actually been released yet) [Cake.Chocolatey.Module](https://github.com/cake-contrib/Cake.Chocolatey.Module) which would let you add this:

` #tool choco:?package=curl`

to the top of your build script, and assuming that you have chocolatey installed already, it would perform the installation of the tool.

**Comment by ecampidoglio** [comment]
@matkoch Did this answer your question?

**Comment by matkoch** [comment]
Probably @gep13 s answer is the right, but I ended up building my own build tool. So this is no longer relevant to me. I will close this anyhow.
