### ISSUE TITLE
Add support for reporting HTTP errors

### ISSUE THREAD

**Issue by ecampidoglio** [ecampidoglio/Cake.Curl#8]
When HTTP servers fail to fulfill a request, they will often return an HTML page with the error information to the client. In situations like these, curl will simply send the content of the error page to stdout and exit with a _zero_ exit code. While this may be fine at the command line, it can be quite problematic in scripts, since it may lead to false positives. 😱

Fortunately, we can tell curl to consider HTTP errors (4xx and 5xx) for what they are and exit with a _non-zero_ status code by passing it the [`-f --fail`](https://curl.haxx.se/docs/manpage.html#-f) option.

Cake.Curl should support that in the `CurlSettings` class.

**Comment by deqenq** [comment]
Hello, can I work on this as my first contribution?

**Comment by ecampidoglio** [comment]
@deqenq Sure! Let me know if you have any questions. 🙂

**Comment by deqenq** [comment]
PR sent

**Comment by ecampidoglio** [comment]
@deqenq Merged in 89e2235. Thank you for your contribution. 🎉
